import sys
import pandas as pd
import quantstats as qs

# Check if the correct number of command-line arguments are provided.
if len(sys.argv) != 3:
    print("Usage: python create_report.py <input_csv_path> <output_html_path>")
    sys.exit(1)

# Get file paths from command-line arguments.
input_csv = sys.argv[1]
output_html = sys.argv[2]
report_title = "Janus Backtest Report"

print(f"Reading equity curve from: {input_csv}")
print(f"Saving QuantStats report to: {output_html}")

# Load the CSV file generated by Janus.
equity_df = pd.read_csv(input_csv, index_col='date', parse_dates=True)

# Generate the quantstats report.
qs.reports.html(equity_df['value'], output=output_html, title=report_title)

print("Report generation complete.")